# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ancfreq_c: Calculating the allele frequency in two different ancestral population
#'
#' @param n an integer, the number of individuals contain in the input
#' @param type 1 or 2, specifying diploid/haploid data.
#' @param pop1 the dir of a file containing individuals belonging to reference population 1
#' @param pop2 the dir of a file containing individuals belonging to reference population 2
#' @param input the dir of the input genolik file
#' @param output the dir of the output ancfreq file
#' @export
ancfreq_c <- function(n, type, pop1, pop2, input, output) {
    invisible(.Call(`_rLCLAE_ancfreq_c`, n, type, pop1, pop2, input, output))
}

#' filt1_dip: transforming the phred score to relative genotype likelihood
#'
#' @param n an integer, the number of individuals contain in the vcf
#' @param input a string, the dir to cleaned vcf file
#' @param output a string, the dir to the output file
#' @export
filt1_dip <- function(n, input, output) {
    invisible(.Call(`_rLCLAE_filt1_dip`, n, input, output))
}

#' filt1_hap: transforming the phred score to relative genotype likelihood
#'
#' @param n an integer, the number of individuals contain in the vcf
#' @param input a string, the dir to cleaned vcf file
#' @param output a string, the dir to the output file
#' @export
filt1_hap <- function(n, input, output) {
    invisible(.Call(`_rLCLAE_filt1_hap`, n, input, output))
}

#' GL=10^(-pl)
#'
#' @param x A single double.
#' @export
glpow <- function(x) {
    .Call(`_rLCLAE_glpow`, x)
}

