# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' GL=10^(-pl)
#'
#' @param x A single double.
#' @export
glpow <- function(x) {
    .Call('_rLCLAE_glpow', PACKAGE = 'rLCLAE', x)
}

